### ISSUE TITLE
Comment '' was not found error

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#42]
Just had a user email me about an error that happens while making a comment on my site. Tested it and, yeah, seems this is happening with every version since v1.5.72. Any version after that tosses this error. Here's what's in the error log:

```
[2020-07-19 18:58:27] production.ERROR: Statamic\Addons\Meerkat\Comments\CommentNotFoundException: Comment '' was not found. in /home/runcloud/webapps/velonut/site/addons/Meerkat/Comments/CommentManager.php:87
Stack trace:
#0 /home/runcloud/webapps/velonut/site/addons/Meerkat/Comments/Stream.php(284): Statamic\Addons\Meerkat\Comments\CommentManager->findOrFail('')
#1 /home/runcloud/webapps/velonut/site/addons/Meerkat/MeerkatController.php(704): Statamic\Addons\Meerkat\Comments\Stream->attachReply('', Object(Statamic\Addons\Meerkat\Forms\Submission))
#2 [internal function]: Statamic\Addons\Meerkat\MeerkatController->postSocialize()
#3 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#4 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): Illuminate\Container\Container->call(Array, Array)
#5 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): Illuminate\Container\Container->callClass('Statamic\\Addons...', Array, NULL)
#6 /home/runcloud/webapps/velonut/statamic/core/Http/Controllers/StatamicController.php(124): Illuminate\Container\Container->call('Statamic\\Addons...', Array)
#7 /home/runcloud/webapps/velonut/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Controllers\StatamicController->callControllerMethod('Meerkat', 'postSocialize', NULL)
#8 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Meerkat', 'socialize')
#9 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#10 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('controllerTrigg...', Array)
#11 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'controllerTrigg...')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'controllerTrigg...')
#18 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'controllerTrigg...')
#19 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /home/runcloud/webapps/velonut/site/addons/SeoPro/Middleware/GenerateReport.php(13): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Statamic\Addons\SeoPro\Middleware\GenerateReport->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#34 /home/runcloud/webapps/velonut/site/addons/Redirects/Middleware/RedirectsMiddleware.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Statamic\Addons\Redirects\Middleware\RedirectsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#37 /home/runcloud/webapps/velonut/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /home/runcloud/webapps/velonut/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /home/runcloud/webapps/velonut/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /home/runcloud/webapps/velonut/index.php(167): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}  
```

**Comment by jeffwhitfield** [comment]
Ok, traced it down to a part in the MeerkatController.php file. I think this will fix it:

```
        if (isset($fields['ids']) && !empty($fields['ids'])) {
            if (is_array($fields['ids']) && count($fields['ids']) > 0) {
                $replyingTo = $fields['ids'][0];
            } else {
                $replyingTo = $fields['ids'];
            }

            $isReply = true;
        }
```

Basically, you have to make sure that the variable isn't empty which, even if it's an array, should evaluate to false if there's something there. Did this and the error went away.

However, I did notice in the process of testing this that the reCaptcha add-on isn't working so...will have to look at that.

**Comment by JohnathonKoster** [comment]
@jeffwhitfield Good catch; I'll get that updated very soon.

Any specific issues your facing with reCaptcha and Meerkat to help narrow down issues? Thanks!

**Comment by JohnathonKoster** [comment]
@jeffwhitfield v1.5.86 has been released to the Marketplace, an improved reply ID check is in place, as well as a bug fix for an issue that would cause unbalanced error keys and messages from being generating (and throwing a fatal error) when an exception occurs when submitting a comment.

I'll keep this open for a bit until I hear back from you :)
